//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace masterfloor.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialType
    {
        public string ID { get; set; }
        public string MaterialType1 { get; set; }
        public double PercentageOfMaterialDefects { get; set; }
    }
}
