//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace masterfloor.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Partner()
        {
            this.Sales = new HashSet<Sales>();
        }
    
        public int ID { get; set; }
        public int TypePartner { get; set; }
        public string NameOfPartner { get; set; }
        public string Director { get; set; }
        public string Email { get; set; }
        public string Number { get; set; }
        public string PartnerAddress { get; set; }
        public string TIN { get; set; }
        public int rating { get; set; }
    
        public virtual TypePartner TypePartner1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sales> Sales { get; set; }
    }
}
