//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace masterfloor.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public int ID { get; set; }
        public int Product { get; set; }
        public int Partner { get; set; }
        public int Quantity { get; set; }
        public System.DateTime DateOfSale { get; set; }
    
        public virtual Partner Partner1 { get; set; }
        public virtual ProductImport ProductImport { get; set; }
    }
}
